---
title: "Nepal Tourism Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll

---

```{r global, message=FALSE, warning=FALSE, include=FALSE}
source('scripts/library.R')
source('scripts/visualize.R')
source('scripts/country.R')
source('scripts/visitor.R')
```

Home 
=====================================  
    
Column {.sidebar}
-----------------------------------------------------------------------


Column3
-----------------------------------------------------------------------


Visitors
=====================================     

Row {data-width=150}
-----------------------------------------------------------------------

### Tourist Arrival 2018 {.value-box}

```{r}
articles <- tourist_arrival_average_length_stay$Number%>% tail(1)
valueBox(articles, icon = "fa-pencil")
```

### Average Stay 2018 {.value-box}

```{r}
comments <- tourist_arrival_average_length_stay$`Average Length of Stay`%>% tail(1) 
valueBox(comments, icon = "fa-comments")
```


 Column {.tabset .tabset-fade data-width=700 .colored }
-----------------------------------------------------------------------
   
### Chart 0 {.no-padding}

```{r}
tourist_arrival_average_length_stay <- read_excel("data/tourist_arrival_average_length_stay.xlsx")
```


```{r}
hchart(tourist_arrival_average_length_stay,"spline", hcaes(x = Year,y = Number),name = "Number of Tourist")

```

    
### Tourist Arrival {.no-padding}

```{r}
page_38_tourist_arrival_nationality_month <- read_excel("data/page_38_tourist_arrival_nationality_month.xlsx")
```

```{r}
ggplotly(num_tourist)%>% config(displayModeBar = F)
```


    
### Tourist Arrival By Gender {.no-padding}

```{r}
ggplotly(tourist_arrival_sex_chart)%>% config(displayModeBar = F)
```

Row {data-height=450}
-------------------------------------
   
### Chart 2

```{r}

ggplotly(ave_tourist_stay)%>% config(displayModeBar = F)
```   
    
### Chart 3

```{r}

```

Country 
=====================================     
   
Row {data-height=600}
-------------------------------------

### Tourist By Country

```{r}

tourist_by_country_chart
```


   
### Tourist By Nationality

```{r}
tourist_arrival_country_time
```   
    

NewPage1 {data-navmenu="Region" data-icon="fa-list"}
=====================================     
   
Row {data-height=600}
-------------------------------------
=======


NewPage1 {data-navmenu="Purpose of Visit" data-icon="fa-list"}
=======

Row {data-height=600}
-------------------------------------


### Chart 1

```{r}
plot_pilgrimage_purpose  
```

### Chart 2

```{r}
plot_business_purpose
```

### Chart 3

```{r}
plot_trekking_purpose

```

Row {data-height=600}
-------------------------------------


### Chart 4

```{r}
plot_official_purpose
```

### Chart 5

```{r}
plot_conv_conf_purpose
```

### Chart 6

```{r}
plot_others_purpose
```


NewPage1 {data-navmenu="Economic Context" data-icon="fa-list"}
=====================================     
   
Row {data-height=400}
-------------------------------------

### Chart 1

```{r}

ggplotly(GROSS_FOREIGN_EXCHANGE_EARNINGS_FROM_TOURISM_NRS_chart) %>% config(displayModeBar = F)
```


### Chart 0

```{r}
ggplotly(GROSS_FOREIGN_EXCHANGE_EARNINGS_FROM_TOURISM_US_chart) %>% config(displayModeBar = F)

```

   
### Chart 2

```{r}
ggplotly(gdp_chart) %>% config(displayModeBar = F)

```   


Hospitality
==============================================

